### ISSUE TITLE
Changing the year in the admin settings results in a 500 error

### ISSUE THREAD

**Issue by theodorsm** [itdagene-ntnu/itdagene#205]
Changing the year to anything else than 2020 results in a 500 error on the frontpage.

![image](https://user-images.githubusercontent.com/55149662/105743320-cacc5f80-5f3c-11eb-9fad-ce511f5ff3df.png)

![image](https://user-images.githubusercontent.com/55149662/105743229-c142f780-5f3c-11eb-8c68-17373c4b7869.png)

There seems to be some issues with the default start-date in Preference: https://github.com/itdagene-ntnu/itdagene/blob/1d70ca2d282527c02d863e22b5a22a8c404fe610/itdagene/core/models.py#L145

![image](https://user-images.githubusercontent.com/55149662/105744641-b3da3d00-5f3d-11eb-888d-ba7e6f5ed61e.png)

**Comment by theodorsm** [comment]
It also seems that the year is automaticlly set to 2021 when show collaborators is set to false in 2020.

**Comment by LorgeN** [comment]
Should be resolved by #207
